=== wuancake-backup/wuancake_php/Gtacer/xml/DTD/movies.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT movies (movie+)>
<!ELEMENT movie (title,actor+,rating)>
<!ELEMENT title (#PCDATA)>
<!ELEMENT actor (#PCDATA)>
<!ELEMENT rating (#PCDATA)>

<!ELEMENT test ANY>		<!-- 根下可以放任意子元素 -->
<!ELEMENT br EMPTY>		<!-- 规定该标签为空标记(单标记) -->

<!ELEMENT html (body)>
<!ELEMENT strong (#PCDATA)>
<!ELEMENT body (#PCDATA|strong)*>	<!-- 混合元素，*不能省略 -->

=== wuancake-backup/wuancake_php/Gtacer/xml/DTD/movies.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--外部引用-->
<!DOCTYPE movies SYSTEM "movies.dtd">	
<!--内部引用-->
<!DOCTYPE movies [	
	<!ELEMENT movies (movie+)>
	<!ELEMENT movie (title,actor+,rating*)>
	<!ELEMENT title (#PCDATA)>
	<!ELEMENT actor (#PCDATA)>
	<!ELEMENT rating (#PCDATA)>
]>
<movies>
	<movie>
		<title>123123</title>
		<actor>123123</actor>
		<rating>123123</rating>
	</movie>
	<movie>
		<title>12312</title>
		<actor>12313</actor>
		<rating>123123</rating>
	</movie>
</movies>
